version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env 
    networks:
      - quicknotes-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - quicknotes-net
    restart: unless-stopped

# 👇 Custom network definition
networks:
  quicknotes-net:
    driver: bridge
